package com.example.supermarket.model;

public enum NotificationType {
    ORDER_CONFIRMED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    ORDER_CANCELLED,
    DELIVERY_CREATED,
    OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    SUPPORT_REPLY,
    SUPPORT_STATUS_UPDATE,
    CANCELLATION_REQUESTED,
    CANCELLATION_APPROVED,
    CANCELLATION_REJECTED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_COMPLETED,
    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    REFUND_COMPLETED
}

